# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 685052d3ae1cd5879da453a47420a2fe965ea0581e7c66e6215c4783f02f33151370110ac0f2b6f16549d8fe7b1db4483c72b6ed80587ef76de58f290eda5110

test:
  secret_key_base: 8bc34a3e3c7b04e5e2549f515c9e5e4dc6456e963fc656069ed8081314bf19f390820ce0a66d822c17bf9a6edab0026ee89fd436ae13203ecef76b7e2951d655

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
